services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver-shopproject
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Pass1234$
    ports:
      - 4000:1433
  
  identity-server:
    depends_on: [ sqlserver ]
    build:
      context: ./DuendeIdentityServer/.
      dockerfile: Dockerfile
    image: vazaras/shopproject-identity-server
    container_name: shopproject-identity-server
    ports:
      - 5001:443
      - 5000:80
  
  api:
    depends_on: [ identity-server ]
    build:
      context: ./ShopProject.Api/.
      dockerfile: Dockerfile
    image: vazaras/shopproject-api
    container_name: shopproject-api
    ports:
      - 6001:443
      - 6000:80
  
  frontend:
    depends_on: [ api ]
    build:
      context: ./ShopProject.Client/.
      dockerfile: Dockerfile
    image: vazaras/shopproject-frontend
    container_name: shopproject-frontend
    ports:
      - 7001:443
      - 7000:80
